name: ds
channels:
 - conda-forge
 - gaiar
 - numba
 - programfan 
 - smartag

dependencies:
 - bokeh
 - colorcet
 - graphviz
 - python-graphviz
 - dask
 - distributed
 - geoviews
 - holoviews
 - ipython
 - jupyter
 - matplotlib
 - networkx>=2.0
 - numba
 - numpy
 - pandas >=0.24.1
 - param
 - python
 - requests
 - scikit-image
 - scipy
 - shapely
 - snappy
 - statsmodels
 - streamz
 - xarray
